### ISSUE TITLE
sidebar addons

### ISSUE THREAD

**Issue by RyoutaPL** [forumthemer/eles-phpbb-forum-theme#11]
Hello,
How to add more addnons to sidebar ? Can u help me?

**Comment by forumthemer** [comment]
Hello!
Yes I can!
- Do you need more than the 5 available widget areas?
- Which addons you want to add?

**Comment by RyoutaPL** [comment]
I need to add donation bar to sidebar.

**Comment by forumthemer** [comment]
You can add it via the custom code widgets, no?
If you have the code for it.

Or is it an extension?
