### ISSUE TITLE
Error with NPM Install in Eles-Child Directory

### ISSUE THREAD

**Issue by C-Holzer** [forumthemer/eles-phpbb-forum-theme#16]
I followed the steps you provided for advanced customization but when I ran `npm install` in the eles-child directory

npm is reporting an error with 'bower install' and I attached a pdf of the debug log.

[npm-debug-log.pdf](https://github.com/forumthemer/eles-phpbb-forum-theme/files/441184/npm-debug-log.pdf)

**Comment by forumthemer** [comment]
Hi!

I am not able to reproduce the issue, please provide more info about your system.

Cheers!
