### ISSUE TITLE
Recent Topics show topics users aren't authorized for

### ISSUE THREAD

**Issue by JmzTaylor** [forumthemer/eles-phpbb-forum-theme#19]
If you enable the recent topics widget in the sidebar, it shows threads that the user can't access.  For example a topic created in a forum that is only accessible to admins, shows up in the recent topics.  Obviously, the user can't access it, but I don't think it should be listed there as topics may not be wanted to show publicly.

**Comment by forumthemer** [comment]
Hi!

Thank you for reporting this issue!
It will be fixed in the next version.

Best regards!
