### ISSUE TITLE
Background coming through popup

### ISSUE THREAD

**Issue by JmzTaylor** [forumthemer/eles-phpbb-forum-theme#20]
The post actions are showing through the pop-up when using quick-mod tools.  

Also, in theory the quick-mods selection should be closed when an action is clicked.

![untitled](https://cloud.githubusercontent.com/assets/1208190/19778468/85c921a0-9c42-11e6-9513-ea4731c55f55.png)

**Comment by forumthemer** [comment]
Hi!

This bug is going to be fixed in version 2.0 (the next version).

Cheers!
