### ISSUE TITLE
quick mode tools delete option Bug

### ISSUE THREAD

**Issue by JuryLeague** [forumthemer/eles-phpbb-forum-theme#22]
how to resolve this one..on the view topic and on the Quick Mod tools and delete option i saw this error [phpBB Debug] PHP Warning: in file [ROOT]/phpbb/user.php on line 513: sprintf(): Too few arguments

**Comment by JuryLeague** [comment]
helow there

**Comment by forumthemer** [comment]
Hi!

This has nothing to do with Eles. Eles doesn't change the **user.php** file.
Please check your server configuration to find out why `sprintf()` fails.
