### ISSUE TITLE
Bug Else template 

### ISSUE THREAD

**Issue by Deus33** [forumthemer/eles-phpbb-forum-theme#23]
Hello, I show you bugs that I have on my forum
Sorry for my bag language, I am French ;)

![capture d ecran 2016-11-28 a 23 42 53](https://cloud.githubusercontent.com/assets/24235839/20689682/f9378d96-b5c6-11e6-828d-6c538016f14b.png)
![capture d ecran 2016-11-28 a 23 43 21](https://cloud.githubusercontent.com/assets/24235839/20689805/6bfcdc96-b5c7-11e6-8403-20a25e07460d.png)
![capture d ecran 2016-11-28 a 23 45 00](https://cloud.githubusercontent.com/assets/24235839/20689691/023f9d52-b5c7-11e6-8b2f-8e6382473c64.png)
![capture d ecran 2016-11-28 a 23 45 19](https://cloud.githubusercontent.com/assets/24235839/20689716/1e3685c0-b5c7-11e6-9000-edb19fa9e710.png)

![capture d ecran 2016-11-28 a 23 35 56](https://cloud.githubusercontent.com/assets/24235839/20689699/0902b80e-b5c7-11e6-9033-7f0d827d5aaf.png)

**Comment by ovitrif** [comment]
Hi!

I checked but the bugs that you are pointing are not in the code.
Are you sure you didn't edited the code and saved it afterwards?

Cheers

**Comment by forumthemer** [comment]
Hi!

I checked the code but these "bugs" are not there.
Are you sure you didn't accidentally edited the files and saved them with there errors?

Cheers
