### ISSUE TITLE
Recents widget with username colour (from usergroup)

### ISSUE THREAD

**Issue by Nyendra** [forumthemer/eles-phpbb-forum-theme#24]
As asked on ThemeForest, suggestion for changing the recents widget to include the username colour from the usergroup.

modify file:
`ext/eles/coreframe/inc/widgets_service.php`

alter (line 98):
`u.username`
to:
`u.username,`

after (line 98):
`u.username,`
new line (line 99):
`g.group_colour`

alter (line 104):
`. USERS_TABLE . ' u ' . '`
to:
`. USERS_TABLE . ' u, '`

For the following edit I'm not sure, as I used `bb_groups g` there since I don't know if the variable `GROUPS_TABLE` exists.

after (line 104):
`. USERS_TABLE . ' u, '`
new line (line 105);
`. GROUPS_TABLE . ' g ' . '`

after (line 114):
`AND p.poster_id = u.user_id`
new line (line 115):
`AND u.group_id = g.group_id`

alter (line 126):
`$author = $row['username'];`
to:
`$author = "<span style=\"color: #".$row['group_colour']."\">".$row['username']."</span>";`

after (line 126):
`$author = "<span style=\"color: #".$row['group_colour']."\">".$row['username']."</span>";`
new line (line 127):
`$author_clean = $row['username'];`

after (line 139):
`'AUTHOR' => $author,`
new line (line 140):
`'AUTHOR_CLEAN' => $author_clean,`

modify file:
`ext/eles/coreframe/styles/eles/templates/widgets/recents.html`

alter (line 7):
`title="{L_POST_BY_AUTHOR} {c_widget_recents.AUTHOR} &raquo; {c_widget_recents.TIMESTAMP}"`
to:
`title="{L_POST_BY_AUTHOR} {c_widget_recents.AUTHOR_CLEAN} &raquo; {c_widget_recents.TIMESTAMP}"`

That should be all. With the exception of using `GROUPS_TABLE` as commented this is working for me.

**Comment by forumthemer** [comment]
Hi!

Many thanks for your detailed guide!
I integrated this and will have it available in the next release.

Cheers
