### ISSUE TITLE
Recent Topics for phpBB 3.2 Error

### ISSUE THREAD

**Issue by thekendog** [forumthemer/eles-phpbb-forum-theme#27]
When installing the latest release candidate for Recent Topics on 3.2 the topics all show below the main list of forums and shows twice. Also, when it is enabled the page never loads completely, I get the spinning icon continuously.

**Comment by ovitrif** [comment]
The issue will be fixed in the next version

**Comment by thekendog** [comment]
This still isn't fixed with the latest version.  I'm running the latest version of the theme, forum software, and the plugin and now the recent topics display at the top and bottom no matter what.  Also, the icons for the top box are broken.
