### ISSUE TITLE
re-Captcha 2.0 is not working with the theme, shows version 1.0 and never solves

### ISSUE THREAD

**Issue by souldesigns** [forumthemer/eles-phpbb-forum-theme#30]
When I enable Captcha 2.0 from ACP it shows the correct re-Captcha version in the admin for demo but on the front-end with Eles theme it shows the older version i.e. Captcha 1.0 and even it does not solve no matter how many correct attempts you make.

Hoping this issue be fixed ASAP as my forum is heavily under bot attack, these bots seem to bypass/solve the captcha methods built inside phpBB !

thanks.

**Comment by forumthemer** [comment]
Hi!

Please check if you have downloaded and installed th :)e latest Eles version.
This issue was already reported and it has been fixed in version 2.1.0.

Here's the changelog:
https://github.com/forumthemer/eles-phpbb-forum-theme/blob/master/CHANGELOG.md#210---06-mar-2017---feature-release

I tested it and it works :)

**Comment by souldesigns** [comment]
I did actually download the latest update and updated the forum but still it did not work, I am going to try  again downloading from Envato and update with the issue !

**Comment by forumthemer** [comment]
You are trying to use the recaptcha with 1 click, right?

**Comment by souldesigns** [comment]
I think these screen-shots explain it better, when I enable re-Captcha from admin, front-end has reCaptcha 1.0 :)

http://www.souldesigns.net/work/reCaptcha-2-admin.jpg
http://www.souldesigns.net/work/reCaptcha-font-end-after-enabling.jpg

is this fixed in the new update?

thanks.

**Comment by souldesigns** [comment]
It worked now ! :+1:
