### ISSUE TITLE
Coreframe Options are Busted

### ISSUE THREAD

**Issue by thekendog** [forumthemer/eles-phpbb-forum-theme#36]
The Coreframe options page is completely busted with the latest update.  I'm on phpBB 3.2 and the latest version of the them.  The custom styles are way off to the right.

https://prnt.sc/gbsfoi

**Comment by jedis00** [comment]
This is an ugly hack, but if you're using Chrome (or even Firefox, maybe)...

1. On the Coreframe Style page, press F12. Then goto the Console tab.
2. Paste the following into the console and press enter:
3. $(document.head).append('<style> .coreframe fieldset { min-width: -webkit-fill-available; } </style>');

You'll magically see the box snap to the bottom and be able to edit it.
NOTE: You'll need to do this on every page reload until they fix it in the next release.

Alternatively, you can make this permanent on your local machine by using a Chrome extension called Stylish (https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en)

1. Install Stylish from the link above
2. Visit the CoreFrame > Style page
3. You'll see an "S" next to your address bar in Chrome. Left click on it and choose the "..." and "Create New Style".
4. Enter style name of "CoreFrame"
5. In the code box, paste the following:
```
.coreframe fieldset {
min-width: -webkit-fill-available;
}
```
6. In the "Applies to" box, choose "URLs starting with" in the dropdown and then make sure the URL has the URL to phpBB forum admin panel: http://www.yoursite.com/forums/adm/index.php
7. Click the Save button.

Now, you'll always see the code box visible on the page. Be sure to remove this style rule after the author patches the issue in the next release!

**Comment by forumthemer** [comment]
Solved in 2.3.0
