### ISSUE TITLE
custom css section is not visible

### ISSUE THREAD

**Issue by TGNC** [forumthemer/eles-phpbb-forum-theme#39]
The custom css section in the Extensions/codeframe/Style is not visible - the layout of the all page is not good, so it is not showing up almost at all (You can only see a glimpse of the section).

![screen shot 2017-10-15 at 18 12 33](https://user-images.githubusercontent.com/6578027/31586054-720095b0-b1d4-11e7-85de-ee28f51e11e7.png)

**Comment by jedis00** [comment]
This is a duplicate of [#36](https://github.com/forumthemer/eles-phpbb-forum-theme/issues/36).

**Comment by forumthemer** [comment]
@jedis00 Thank you for your activity!
You are right, indeed!

I closed this issue, because it is a duplicate of #36
