### ISSUE TITLE
got warning

### ISSUE THREAD

**Issue by phpbbuser** [forumthemer/eles-phpbb-forum-theme#47]
[phpBB Debug] PHP Warning: in file [ROOT]/phpbb/di/container_builder.php on line 146: require(./cache/production/autoload_4335734bbdd20f586549a504dff5f80c.php): failed to open stream: No such file or directory

Every time i login with moderator access this thing happen,

This never happen before using else theme.

I checked the path and i found out that the file autoload_4335734bbdd20f586549a504dff5f80c.php is missing on the directory, for the mean time solution i re-uploaded the file, but everytime i loging again with mod access it happen again...

any solution for this? what went wrong?

**Comment by forumthemer** [comment]
You have to turn off DEV MODE from the coreframe panel :)

That's why it is advised in the documentation to disable it in production
