### ISSUE TITLE
Fancy forum index layout available for all pages (optionally)

### ISSUE THREAD

**Issue by OmenLW** [forumthemer/eles-phpbb-forum-theme#5]
Author: “That’s part of the design of the latest version. The index page is more like a presentation of the forum, while on the other pages, visitors are more interested in the comment, which is why the header doesn’t occupy half of the page.”

Is there any way to let us enable this for all pages on the site? I have the pages extension and use that to make a new home page and it looks funny when my main home page is not as fancy as the forum index. I would like to see it uniform on all pages if possible. The option to allow that would be excellent. Thanks!

**Comment by forumthemer** [comment]
There will be a change in the style which will add the fancy offset to all pages.

Cheers
