### ISSUE TITLE
Online indicator moves with avatar info.

### ISSUE THREAD

**Issue by OkashiiFireclaw** [forumthemer/eles-phpbb-forum-theme#7]
When avatars are set to the left, the online indicator remains on the right. Is there any way to move it to the left along with the rest of the avatar info? 

Thanks :)

**Comment by forumthemer** [comment]
We can implement it as a feature in an upcoming version.

**Comment by forumthemer** [comment]
This behavior is part of the eles style, it will not be changed.

Cheers

**Comment by forumthemer** [comment]
This issue is going to be fixed in version 2.1.

Cheers!
