### ISSUE TITLE
Sidebar is no displayed

### ISSUE THREAD

**Issue by reballinges** [forumthemer/eles-phpbb-forum-theme#9]
The sidebar is not displayed on every page. In the index.php or viewtopic.php and other pages it works perfectly, but posting.php, viewonline.php, faq.php (give examples) not shown.

In pages generated by the “pages” extension or “portal” it does not appear. Only where they are marked in coreframe options.

**Comment by forumthemer** [comment]
Fixed in version 1.6.0

**Comment by reballinges** [comment]
sidebar appears on all pages marked in coreframe options, but not in Board3 Portal
Example: http://www.reballing.es/portal

would have way to implement a "show everywhere" and a "select pages where you show"? Before working perfectly, and for us is a problem losing sidebar

Waiting for your answer. Thank you very much

**Comment by forumthemer** [comment]
The Board3 Portal is not officially supported by Eles, and there is no easy way at the moment to implement a "show everywhere" options, but seen that the current implementation fails in this regard, I think it would be a good idea to reverse the logic, so "Pages to show the sidebar:" will become "Hide sidebar on the following pages:".

This is an easy solution which will fix the issues encountered with the current implementation.

PS, I added a issue https://github.com/forumthemer/eles-phpbb-forum-theme/issues/13 for this change.
